"""initial schema: mws, field_record, asset_evidence (PRD.md §8)

Hand-written (not autogenerated) to guarantee an exact column-by-column
match against PRD §8's SQL block, which is the schema of record.

Revision ID: 0001
Revises:
Create Date: 2026-09-28
"""

from __future__ import annotations

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "mws",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("project_id", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("district", sa.Text(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.Geometry(geometry_type="MULTIPOLYGON", srid=4326, spatial_index=False),
            nullable=False,
        ),
        sa.Column("baseline_start", sa.Date(), nullable=True),
        sa.Column("baseline_end", sa.Date(), nullable=True),
        sa.Column("latest_start", sa.Date(), nullable=True),
        sa.Column("latest_end", sa.Date(), nullable=True),
        sa.Column("is_synthetic_boundary", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_mws"),
    )
    op.create_index("idx_mws_geom", "mws", ["geom"], unique=False, postgresql_using="gist")

    op.create_table(
        "field_record",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("work_code", sa.Text(), nullable=True),
        sa.Column("mws_id", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("activity", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("gps_accuracy_m", sa.REAL(), nullable=True),
        sa.Column("orientation", sa.REAL(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("photo1_url", sa.Text(), nullable=True),
        sa.Column("photo2_url", sa.Text(), nullable=True),
        sa.Column("photo1_phash", sa.Text(), nullable=True),
        sa.Column("photo2_phash", sa.Text(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("observer_id", sa.Text(), nullable=True),
        sa.Column("observer_name", sa.Text(), nullable=True),
        sa.Column("organisation", sa.Text(), nullable=True),
        sa.Column(
            "geom", geoalchemy2.Geometry(geometry_type="POINT", srid=4326, spatial_index=False), nullable=False
        ),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("photo_source", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["mws_id"], ["mws.id"], name="fk_field_record_mws_id"),
        sa.PrimaryKeyConstraint("id", name="pk_field_record"),
    )
    op.create_index("idx_field_record_geom", "field_record", ["geom"], unique=False, postgresql_using="gist")

    op.create_table(
        "asset_evidence",
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("geo_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("geo_score", sa.Integer(), nullable=True),
        sa.Column("ai_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("visual_score", sa.Integer(), nullable=True),
        sa.Column("sat_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("satellite_score", sa.Integer(), nullable=True),
        sa.Column("temporal_score", sa.Integer(), nullable=True),
        sa.Column("evidence_score", sa.Integer(), nullable=True),
        sa.Column("band", sa.Text(), nullable=True),
        sa.Column("reviewer_decision", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"], ["field_record.id"], name="fk_asset_evidence_record_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("record_id", name="pk_asset_evidence"),
    )


def downgrade() -> None:
    op.drop_table("asset_evidence")
    op.drop_index("idx_field_record_geom", table_name="field_record")
    op.drop_table("field_record")
    op.drop_index("idx_mws_geom", table_name="mws")
    op.drop_table("mws")
