"""Provenance entries owned by backend-engineer (Reality Pass R3 — the
Marigaon work-code registry, and R4 — this endpoint itself plus the
district-level geotag coverage table already shipped for FR5.5).

See app/services/provenance_sources/__init__.py for how this fits into
GET /provenance, and app/schemas/provenance.py for the entry shape.
"""

from __future__ import annotations

from app.schemas.provenance import ProvenanceEntry

_GOV_LICENCE_NOTE = (
    "Public government data (Department of Land Resources, Ministry of Rural "
    "Development, GoI). No formal open-data licence tag found on the portal "
    "itself (unlike data.gov.in's GODL-India) — cited with source URL + "
    "retrieved_at per docs/REAL_DATA_PLAN.md §2's own caveat, fetched once, "
    "politely (<=1 req/sec, identified User-Agent), never live from a request "
    "path."
)

ENTRIES: list[ProvenanceEntry] = [
    ProvenanceEntry(
        name="WDC-PMKSY 2.0 MIS — Report GT2, State/District geotag coverage",
        source_url="https://wdcpmksy.dolr.gov.in/getAllAssetGeoData",
        licence=_GOV_LICENCE_NOTE,
        retrieved_at="2026-09-28",
        is_synthetic=False,
        photo_source=None,
        used_for="GET /districts/geotag-coverage — district-level choropleth (FR5.5)",
        notes=(
            "51 districts across Assam (31), Meghalaya (12), Tripura (8). "
            "Report's own 'as on' timestamp: 28/09/2026. Four Assam districts "
            "report geotagged_works slightly exceeding total_works in the "
            "government's own live MIS (a reconciliation quirk, not a "
            "transcription error here) — see api/app/services/"
            "district_coverage.py's module docstring for the full note. "
            "Cross-checked against R3's independent, more granular fetch "
            "(scripts/fetch_gt2.py) for Morigaon specifically: 309 total / "
            "267 geotagged / 42 non-geotagged in both — no discrepancy found."
        ),
        owner="R4/R5.5 backend-engineer",
    ),
    ProvenanceEntry(
        name="WDC-PMKSY 2.0 MIS — Report GT2, Marigaon work-code registry (WDC-1 project)",
        source_url=(
            "https://wdcpmksy.dolr.gov.in/getProjDtlAssetGeoData?projid=90"
            "&stname=ASSAM&distname=MARIGAON&projname=MARIGAON-WDC+-+1+%2F2021-22"
        ),
        licence=_GOV_LICENCE_NOTE,
        retrieved_at="2026-09-28T10:25:58+00:00",
        is_synthetic=False,
        photo_source=None,
        used_for=(
            "GET /programme/marigaon — registry aggregates + exact (computed, not "
            "estimated) Pre/Mid/Post moderation backlog; scripts/output/registry/"
            "workcodes_marigaon_wdc1.csv (per-work-code detail, 240 geotagged rows)"
        ),
        notes=(
            "Full drill-down chain fetched: state (getAllAssetGeoData) -> district "
            "(getDistWiseAssetGeoData, stcode=18 ASSAM) -> project "
            "(getProjWiseAssetGeoData, dcode=296 MARIGAON) -> work-code detail "
            "(getProjDtlAssetGeoData, projid=90, 'MARIGAON-WDC - 1 /2021-22'). "
            "263 total work codes, 240 geotagged (73 NRM / 11 EPA / 112 Livelihood "
            "/ 67 Production). Pre-implementation moderation backlog: 51.2% of the "
            "240 geotagged work codes are 'Yet to Moderate' (exact count 123/240, "
            "not estimated — see scripts/output/registry/programme_marigaon.json). "
            "Raw HTML cached at scripts/cache/gt2/ (gitignored — reproducible via "
            "`python scripts/fetch_gt2.py`, which reads that cache and makes zero "
            "new requests unless it's missing or --force is passed). "
            "Activity -> PRD §15.1 category mapping is docs/REAL_DATA_PLAN.md §5's "
            "own proposed table (keyword-based); 4 activities not covered by that "
            "table default to OM ('Others') and are listed explicitly in "
            "programme_marigaon.json's `unmapped_activities` for human review, "
            "never silently guessed as something more specific."
        ),
        owner="R3 backend-engineer",
    ),
    ProvenanceEntry(
        name="Synthetic Drishti-schema seed field records (Phase 1 demo dataset)",
        source_url=None,
        licence="N/A — generated by this project, not sourced from a third party",
        retrieved_at=None,
        is_synthetic=True,
        photo_source="ai_generated",
        used_for="Phase 1 seed data powering the map dashboard demo (points + photos)",
        notes=(
            "scripts/seed_data.py / scripts/seed/generate_records_csv.py: points "
            "placed programmatically inside the demo watershed boundary polygon "
            "(Shapely random-point-in-polygon), never hand-typed. Photos are "
            "Pollinations.ai-generated JPEGs with matching (or, for 3-4 "
            "deliberately-bad rows, deliberately mismatched/missing) EXIF "
            "GPS/timestamp tags, per PRD FR1.5/FR2.0 — no field visit occurred in "
            "this timeline. Every row carries is_synthetic=true and "
            "photo_source='ai_generated' at insert time, no exceptions "
            "(CLAUDE.md non-negotiable). Never attached to a real government work "
            "code — this dataset and R3's real work-code registry above are kept "
            "fully separate, per docs/REAL_DATA_PLAN.md's hard rule."
        ),
        owner="Phase 1 backend-engineer",
    ),
]
