/**
 * Mock for `GET /provenance`, mirroring a real captured live response
 * (2026-09-28) verbatim — all 12 real dataset citations, used by beat 7's
 * provenance panel / Methods & limits drawer.
 */
import type { ProvenanceEntry } from '@/types/domain'

const GT2_LICENCE =
  "Public government data (Department of Land Resources, Ministry of Rural Development, GoI). No formal open-data licence tag found on the portal itself (unlike data.gov.in's GODL-India) — cited with source URL + retrieved_at per docs/REAL_DATA_PLAN.md §2's own caveat, fetched once, politely (<=1 req/sec, identified User-Agent), never live from a request path."

const COMMONS_NOTE =
  'Full per-file provenance (title, file_page_url, author, exact licence, retrieved_at) in scripts/real_photos/manifest.json. Methodology + confusion matrix + measured accuracy: docs/CLASSIFIER_BENCHMARK.md and GET /classifier/benchmark.'

export const provenance: ProvenanceEntry[] = [
  {
    name: 'WDC-PMKSY 2.0 MIS — Report GT2, State/District geotag coverage',
    source_url: 'https://wdcpmksy.dolr.gov.in/getAllAssetGeoData',
    licence: GT2_LICENCE,
    retrieved_at: '2026-09-28',
    is_synthetic: false,
    photo_source: null,
    used_for: 'GET /districts/geotag-coverage — district-level choropleth (FR5.5)',
    notes:
      "51 districts across Assam (31), Meghalaya (12), Tripura (8). Report's own 'as on' timestamp: 28/09/2026. Four Assam districts report geotagged_works slightly exceeding total_works in the government's own live MIS (a reconciliation quirk, not a transcription error here). Cross-checked against R3's independent, more granular fetch for Morigaon specifically: 309 total / 267 geotagged / 42 non-geotagged in both — no discrepancy found.",
    owner: 'R4/R5.5 backend-engineer',
  },
  {
    name: 'WDC-PMKSY 2.0 MIS — Report GT2, Marigaon work-code registry (WDC-1 project)',
    source_url:
      'https://wdcpmksy.dolr.gov.in/getProjDtlAssetGeoData?projid=90&stname=ASSAM&distname=MARIGAON&projname=MARIGAON-WDC+-+1+%2F2021-22',
    licence: GT2_LICENCE,
    retrieved_at: '2026-09-28T10:25:58+00:00',
    is_synthetic: false,
    photo_source: null,
    used_for:
      "GET /programme/marigaon — registry aggregates + exact (computed, not estimated) Pre/Mid/Post moderation backlog; scripts/output/registry/workcodes_marigaon_wdc1.csv (per-work-code detail, 240 geotagged rows)",
    notes:
      "263 total work codes, 240 geotagged (73 NRM / 11 EPA / 112 Livelihood / 67 Production). Pre-implementation moderation backlog: 51.2% of the 240 geotagged work codes are 'Yet to Moderate' (exact count 123/240, not estimated). Activity -> PRD §15.1 category mapping is docs/REAL_DATA_PLAN.md §5's own proposed table (keyword-based); 4 activities not covered default to OM and are listed explicitly in `unmapped_activities` for human review.",
    owner: 'R3 backend-engineer',
  },
  {
    name: 'Synthetic Drishti-schema seed field records (Phase 1 demo dataset)',
    source_url: null,
    licence: 'N/A — generated by this project, not sourced from a third party',
    retrieved_at: null,
    is_synthetic: true,
    photo_source: 'ai_generated',
    used_for: 'Phase 1 seed data powering the map dashboard demo (points + photos)',
    notes:
      'Points placed programmatically inside the demo watershed boundary polygon (Shapely random-point-in-polygon), never hand-typed. Photos are Pollinations.ai-generated JPEGs with matching (or, for planted bad rows, deliberately mismatched/missing) EXIF GPS/timestamp tags — no field visit occurred in this timeline. Every row carries is_synthetic=true and photo_source=\'ai_generated\' at insert time, no exceptions. Never attached to a real government work code.',
    owner: 'Phase 1 backend-engineer',
  },
  {
    name: 'Real-photo classifier benchmark — SM (Structural measures, check dams)',
    source_url: 'https://commons.wikimedia.org/wiki/Category:Check_dams_in_India',
    licence: 'CC BY-SA 3.0 / 4.0, CC0, Public domain (varies per file)',
    retrieved_at: '2026-09-28',
    is_synthetic: false,
    photo_source: null,
    used_for: 'Real-photo classifier accuracy benchmark ground truth (10 photos)',
    notes: COMMONS_NOTE,
    owner: 'R5 vision-ai-engineer',
  },
  {
    name: 'Real-photo classifier benchmark — PT (Pond-Tanks)',
    source_url: 'https://commons.wikimedia.org/wiki/Category:Ponds_in_India',
    licence: 'CC BY-SA 3.0 / 4.0 (varies per file)',
    retrieved_at: '2026-09-28',
    is_synthetic: false,
    photo_source: null,
    used_for: 'Real-photo classifier accuracy benchmark ground truth (6 photos)',
    notes: COMMONS_NOTE,
    owner: 'R5 vision-ai-engineer',
  },
  {
    name: 'Real-photo classifier benchmark — BN (Bunds)',
    source_url: 'https://commons.wikimedia.org/wiki/Category:Levees_in_India',
    licence: 'CC BY 3.0',
    retrieved_at: '2026-09-28',
    is_synthetic: false,
    photo_source: null,
    used_for: 'Real-photo classifier accuracy benchmark ground truth (5 photos)',
    notes: `Baitarani river embankment restoration series, Odisha, one photographer. ${COMMONS_NOTE}`,
    owner: 'R5 vision-ai-engineer',
  },
  {
    name: 'Real-photo classifier benchmark — AM (Agronomic measures)',
    source_url: 'https://commons.wikimedia.org/wiki/Category:Agricultural_terraces_in_Kerala',
    licence: 'CC BY-SA 2.0 / 3.0 / 4.0 (varies per file)',
    retrieved_at: '2026-09-28',
    is_synthetic: false,
    photo_source: null,
    used_for: 'Real-photo classifier accuracy benchmark ground truth (5 photos)',
    notes: COMMONS_NOTE,
    owner: 'R5 vision-ai-engineer',
  },
  {
    name: 'Real-photo classifier benchmark — VM (Vegetative measures)',
    source_url: 'https://commons.wikimedia.org/wiki/Category:Reforestation_in_India',
    licence: 'CC BY-SA 3.0 / 4.0 (varies per file)',
    retrieved_at: '2026-09-28',
    is_synthetic: false,
    photo_source: null,
    used_for: 'Real-photo classifier accuracy benchmark ground truth (3 photos)',
    notes: COMMONS_NOTE,
    owner: 'R5 vision-ai-engineer',
  },
  {
    name: 'Real-photo classifier benchmark — LS (Livestock)',
    source_url: 'https://commons.wikimedia.org/wiki/Category:Goats_in_Assam',
    licence: 'CC BY-SA 4.0',
    retrieved_at: '2026-09-28',
    is_synthetic: false,
    photo_source: null,
    used_for: 'Real-photo classifier accuracy benchmark ground truth (3 photos)',
    notes: COMMONS_NOTE,
    owner: 'R5 vision-ai-engineer',
  },
  {
    name: 'Real-photo classifier benchmark — LH (Livelihood)',
    source_url: 'https://commons.wikimedia.org/wiki/Category:Sericulture_in_India',
    licence: 'CC BY 4.0, CC BY-SA 3.0 / 4.0 (varies per file)',
    retrieved_at: '2026-09-28',
    is_synthetic: false,
    photo_source: null,
    used_for: 'Real-photo classifier accuracy benchmark ground truth (5 photos)',
    notes: `Sericulture/handloom + fish-farming photos. ${COMMONS_NOTE}`,
    owner: 'R5 vision-ai-engineer',
  },
  {
    name: 'Real-photo classifier benchmark — NC (Nala-Channels)',
    source_url: 'https://commons.wikimedia.org/wiki/Category:Irrigation_canals_in_India',
    licence: 'CC BY 3.0, CC BY-SA 3.0 / 4.0, CC0 (varies per file)',
    retrieved_at: '2026-09-28',
    is_synthetic: false,
    photo_source: null,
    used_for: 'Real-photo classifier accuracy benchmark ground truth (5 photos)',
    notes: `Small/village-scale channels only — major state infrastructure deliberately excluded as a different scale from a watershed-programme nala/channel work. ${COMMONS_NOTE}`,
    owner: 'R5 vision-ai-engineer',
  },
  {
    name: 'Real-photo classifier benchmark — NONE (deliberate distractors)',
    source_url: 'https://commons.wikimedia.org/wiki/Category:Street_markets_in_India',
    licence: 'CC BY-SA 4.0',
    retrieved_at: '2026-09-28',
    is_synthetic: false,
    photo_source: null,
    used_for: 'Tests whether the classifier over-predicts a PRD §15.1 category on an unrelated real scene (3 photos)',
    notes: COMMONS_NOTE,
    owner: 'R5 vision-ai-engineer',
  },
]
